In [13]:
import pandas as pd
import numpy as np
import random

In [2]:
df = pd.read_excel(r"C:\Users\gopal\OneDrive\Desktop\Healthcare analysis\dataset\Hospital_Management_Records.xlsx")
df.head(10)

,PatientID,PatientName,Age,Gender,PhoneNumber,Email,Address,City,State,RegistrationDate,...,SurgeryDate,FollowUpDate,TotalBillAmount,AmountPaid,PendingAmount,PaymentMode,BillingDate,InsuranceProvider,FeedbackRating,Disease
0,45d3d0ef-38c3-49c9-a0bd-c68d9ee90a0f,Drishya Mammen,25,Female,2416034981,atank@arora-master.net,"40/720, Chakrabarti Circle, Bhilwara-385220",Tadipatri,Bihar,03-10-2024,...,NaN,23-04-2025,80179.16,59341.66,20837.50,Card,13-03-2025,Borah Inc,5,Flu
1,afd50add-bab4-4e63-baca-3d92585821da,Rania Balay,44,Male,912947000000,kaladhruv@ratti.com,"66, Master Nagar, Mumbai-334047",Allahabad,Goa,04-03-2024,...,07-04-2025,01-07-2025,171628.31,17818.53,153809.78,Insurance,03-06-2025,NaN,2,Flu
2,d59f02b8-36be-4450-858f-22940e4d0a9b,Rhea Bhat,44,Other,1714094485,abhalla@batra.com,"013, Jayaraman Chowk, Tiruchirappalli-908041",Asansol,Chhattisgarh,08-02-2025,...,27-03-2025,24-06-2025,184429.53,97493.48,86936.05,UPI,05-04-2025,NaN,1,Cancer
3,d55dfe6a-0da2-4352-8321-15dda501a571,Elakshi Chatterjee,38,Other,910622000000,piyachacko@gmail.com,"H.No. 798, Das Nagar, Ahmednagar 130849",Kulti,Goa,25-07-2024,...,24-12-2024,31-05-2025,39095.10,7275.76,31819.34,UPI,24-02-2025,Khalsa-Bala,4,COVID-19
4,1ce3dd94-318a-494d-8e91-e070237fe54f,Ayesha Toor,75,Female,5104023087,jivika45@hotmail.com,"H.No. 487, Koshy Ganj, Katihar 463550",Ramgarh,Tripura,28-02-2024,...,17-02-2025,06-06-2025,17879.31,10372.96,7506.35,UPI,20-04-2025,NaN,1,Hypertension
5,6feaf91a-799e-40d7-85da-fe3d1a594942,Ela Dixit,16,Other,912777000000,cheemamisha@chakrabarti-baria.com,"H.No. 71, Chand Marg, Tiruvottiyur 432532",Mira-Bhayandar,Jharkhand,02-02-2024,...,NaN,NaN,188989.40,116152.30,72837.10,Insurance,06-11-2024,"Vyas, Ben and Raman",3,Diabetes
6,48cdb1e0-29d7-4ddf-bc9c-b2e6f6f90c1d,Aarush Sule,17,Female,911590000000,zkohli@varty.biz,"90, Bhargava Marg, Bally 402399",Sangli-Miraj & Kupwad,Manipur,26-07-2023,...,10-03-2025,NaN,65484.07,41734.22,23749.85,UPI,15-03-2025,Brahmbhatt-Saxena,2,Flu
7,59ba1a66-dc08-4992-b3cc-6ad653c7db54,Nakul Bir,66,Other,912344000000,jaggimyra@trivedi-wason.com,"H.No. 524, Dasgupta Chowk, Amravati 970307",Rampur,Jharkhand,10-04-2025,...,NaN,NaN,63235.56,51084.39,12151.17,UPI,15-06-2025,NaN,2,Flu
8,bb5d51bf-b451-4989-b384-abdc410e524f,Hunar Bobal,63,Other,9929788387,bhaminivenkatesh@hotmail.com,"493, Bajaj Ganj, Jamshedpur 593268",Belgaum,Arunachal Pradesh,20-11-2023,...,21-08-2024,10-04-2025,89736.48,25293.31,64443.17,Insurance,05-10-2024,"Dey, Dua and Garde",4,Asthma
9,6dedc38d-455e-4f32-9ff4-6bf678d81127,Kartik Sawhney,49,Male,551481678,sarabath@gmail.com,"64, Sawhney Road, Jhansi 135817",Saharsa,Uttar Pradesh,27-02-2025,...,30-03-2025,13-06-2025,85077.67,39249.89,45827.78,Cash,07-06-2025,"Rajagopal, Chana and Bhattacharyya",5,Diabetes

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 35 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   PatientID          10000 non-null  object
 1   PatientName        10000 non-null  object
 2   Age                10000 non-null  int64
 3   Gender             10000 non-null  object
 4   PhoneNumber        10000 non-null  int64
 5   Email              10000 non-null  object
 6   Address            10000 non-null  object
 7   City               10000 non-null  object
 8   State              10000 non-null  object
 9   RegistrationDate   10000 non-null  object
 10  DoctorID           10000 non-null  object
 11  DoctorName         10000 non-null  object
 12  Specialization     10000 non-null  object
 13  Department         10000 non-null  object
 14  DoctorPhone        10000 non-null  int64
 15  ConsultationFee    10000 non-null  int64
 16  AdmissionDate      10000 non-null  object
 17  DischargeDate      10000 non-null  object
 18  RoomType           10000 non-null  object
 19  RoomNumber         10000 non-null  object
 20  BedNumber          10000 non-null  object
 21  AdmissionReason    10000 non-null  object
 22  Diagnosis          10000 non-null  object
 23  TreatmentGiven     10000 non-null  object
 24  SurgeryRequired    10000 non-null  object
 25  SurgeryDate        5047 non-null   object
 26  FollowUpDate       6976 non-null   object
 27  TotalBillAmount    10000 non-null  float64
 28  AmountPaid         10000 non-null  float64
 29  PendingAmount      10000 non-null  float64
 30  PaymentMode        10000 non-null  object
 31  BillingDate        10000 non-null  object
 32  InsuranceProvider  4060 non-null   object
 33  FeedbackRating     10000 non-null  int64
 34  Disease            10000 non-null  object
dtypes: float64(3), int64(5), object(27)
memory usage: 2.7+ MB

In [4]:
df.columns

Index(['PatientID', 'PatientName', 'Age', 'Gender', 'PhoneNumber', 'Email',
       'Address', 'City', 'State', 'RegistrationDate', 'DoctorID',
       'DoctorName', 'Specialization', 'Department', 'DoctorPhone',
       'ConsultationFee', 'AdmissionDate', 'DischargeDate', 'RoomType',
       'RoomNumber', 'BedNumber', 'AdmissionReason', 'Diagnosis',
       'TreatmentGiven', 'SurgeryRequired', 'SurgeryDate', 'FollowUpDate',
       'TotalBillAmount', 'AmountPaid', 'PendingAmount', 'PaymentMode',
       'BillingDate', 'InsuranceProvider', 'FeedbackRating', 'Disease'],
      dtype='object')

In [5]:
df.shape

(10000, 35)

In [6]:
df.describe()

,Age,PhoneNumber,DoctorPhone,ConsultationFee,TotalBillAmount,AmountPaid,PendingAmount,FeedbackRating
count,10000.000000,1.000000e+04,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,45.688200,3.040357e+11,3.110163e+11,898.114900,103340.970290,51022.669835,52318.300455,2.993000
std,25.959738,4.274460e+11,4.299286e+11,347.176305,55896.287403,43855.359707,44235.996999,1.418997
min,1.000000,1.134300e+05,9.081340e+05,300.000000,5034.300000,0.330000,1.950000,1.000000
25%,23.000000,3.795966e+09,3.763893e+09,593.000000,55356.925000,14926.487500,15780.650000,2.000000
50%,46.000000,7.398467e+09,7.524377e+09,898.000000,103522.700000,38649.885000,39998.450000,3.000000
75%,68.000000,9.123692e+11,9.125452e+11,1201.000000,151603.377500,77752.820000,79805.037500,4.000000
max,90.000000,9.199980e+11,9.199880e+11,1500.000000,199980.060000,197567.590000,194625.760000,5.000000

In [7]:
df.loc[158]

PatientID                b8a1119d-09c0-40db-b49a-c96e6ae33eb9
PatientName                                       Rati Sahota
Age                                                        47
Gender                                                   Male
PhoneNumber                                      913880000000
Email                                      tara78@hotmail.com
Address              H.No. 89, Krishnan Ganj, Panihati 853709
City                                                Mangalore
State                                               Jharkhand
RegistrationDate                                   13-01-2025
DoctorID                 92f80dc5-cafc-47bc-912d-04373f1de0c7
DoctorName                                     Aradhya Sekhon
Specialization                               General Medicine
Department                                            Surgery
DoctorPhone                                        9509180256
ConsultationFee                                           359
AdmissionDate                                      26-01-2025
DischargeDate                                      01-04-2025
RoomType                                              Private
RoomNumber                                               R431
BedNumber                                                 B34
AdmissionReason                                       Routine
Diagnosis                                                 Flu
TreatmentGiven                     Sequi qui minima incidunt.
SurgeryRequired                                           Yes
SurgeryDate                                        21-03-2025
FollowUpDate                                       20-06-2025
TotalBillAmount                                      55431.59
AmountPaid                                           54880.77
PendingAmount                                          550.82
PaymentMode                                              Card
BillingDate                                        01-04-2025
InsuranceProvider                                         NaN
FeedbackRating                                              5
Disease                                              Diabetes
Name: 158, dtype: object

In [8]:
df.iloc[2:5]

,PatientID,PatientName,Age,Gender,PhoneNumber,Email,Address,City,State,RegistrationDate,...,SurgeryDate,FollowUpDate,TotalBillAmount,AmountPaid,PendingAmount,PaymentMode,BillingDate,InsuranceProvider,FeedbackRating,Disease
2,d59f02b8-36be-4450-858f-22940e4d0a9b,Rhea Bhat,44,Other,1714094485,abhalla@batra.com,"013, Jayaraman Chowk, Tiruchirappalli-908041",Asansol,Chhattisgarh,08-02-2025,...,27-03-2025,24-06-2025,184429.53,97493.48,86936.05,UPI,05-04-2025,NaN,1,Cancer
3,d55dfe6a-0da2-4352-8321-15dda501a571,Elakshi Chatterjee,38,Other,910622000000,piyachacko@gmail.com,"H.No. 798, Das Nagar, Ahmednagar 130849",Kulti,Goa,25-07-2024,...,24-12-2024,31-05-2025,39095.10,7275.76,31819.34,UPI,24-02-2025,Khalsa-Bala,4,COVID-19
4,1ce3dd94-318a-494d-8e91-e070237fe54f,Ayesha Toor,75,Female,5104023087,jivika45@hotmail.com,"H.No. 487, Koshy Ganj, Katihar 463550",Ramgarh,Tripura,28-02-2024,...,17-02-2025,06-06-2025,17879.31,10372.96,7506.35,UPI,20-04-2025,NaN,1,Hypertension

In [9]:
df.isnull().sum()

PatientID               0
PatientName             0
Age                     0
Gender                  0
PhoneNumber             0
Email                   0
Address                 0
City                    0
State                   0
RegistrationDate        0
DoctorID                0
DoctorName              0
Specialization          0
Department              0
DoctorPhone             0
ConsultationFee         0
AdmissionDate           0
DischargeDate           0
RoomType                0
RoomNumber              0
BedNumber               0
AdmissionReason         0
Diagnosis               0
TreatmentGiven          0
SurgeryRequired         0
SurgeryDate          4953
FollowUpDate         3024
TotalBillAmount         0
AmountPaid              0
PendingAmount           0
PaymentMode             0
BillingDate             0
InsuranceProvider    5940
FeedbackRating          0
Disease                 0
dtype: int64

In [10]:
df["InsuranceProvider"] = df["InsuranceProvider"].fillna("Unknown")

In [11]:
df.dtypes

PatientID             object
PatientName           object
Age                    int64
Gender                object
PhoneNumber            int64
Email                 object
Address               object
City                  object
State                 object
RegistrationDate      object
DoctorID              object
DoctorName            object
Specialization        object
Department            object
DoctorPhone            int64
ConsultationFee        int64
AdmissionDate         object
DischargeDate         object
RoomType              object
RoomNumber            object
BedNumber             object
AdmissionReason       object
Diagnosis             object
TreatmentGiven        object
SurgeryRequired       object
SurgeryDate           object
FollowUpDate          object
TotalBillAmount      float64
AmountPaid           float64
PendingAmount        float64
PaymentMode           object
BillingDate           object
InsuranceProvider     object
FeedbackRating         int64
Disease               object
dtype: object

In [15]:
date_cols = ["RegistrationDate","AdmissionDate","DischargeDate","BillingDate", 'SurgeryDate', 'FollowUpDate']
for col in date_cols:
    df[col] = pd.to_datetime(df[col], format="%d-%m-%Y", dayfirst=True, errors="coerce")

In [18]:
mask = df["SurgeryDate"].notna() & df["FollowUpDate"].isna()
df.loc[mask, "FollowUpDate"] = (
    df.loc[mask, "SurgeryDate"] + pd.Timedelta(days = 7)
)

In [19]:
df.dtypes

PatientID                    object
PatientName                  object
Age                           int64
Gender                       object
PhoneNumber                   int64
Email                        object
Address                      object
City                         object
State                        object
RegistrationDate     datetime64[ns]
DoctorID                     object
DoctorName                   object
Specialization               object
Department                   object
DoctorPhone                   int64
ConsultationFee               int64
AdmissionDate        datetime64[ns]
DischargeDate        datetime64[ns]
RoomType                     object
RoomNumber                   object
BedNumber                    object
AdmissionReason              object
Diagnosis                    object
TreatmentGiven               object
SurgeryRequired              object
SurgeryDate          datetime64[ns]
FollowUpDate         datetime64[ns]
TotalBillAmount             float64
AmountPaid                  float64
PendingAmount               float64
PaymentMode                  object
BillingDate          datetime64[ns]
InsuranceProvider            object
FeedbackRating                int64
Disease                      object
dtype: object

CREATE NEW FEATURES

In [20]:
df["AgeGroup"] = pd.cut(
    df["Age"],
    bins=[0, 18, 35, 50,65, 100],
    labels=["Child", "YoungAdult", "Adult", "Senior", "Elder"]
)

In [21]:
df["HospitalStays"] = (df["DischargeDate"] - df["AdmissionDate"]).dt.days

In [22]:
df["PaymentStatus"] = np.where(
    df["PendingAmount"] == 0,
    "Paid",
    "Pending"
)

In [23]:
df.shape

(10000, 38)

In [25]:
df.to_csv(r"C:\Users\gopal\OneDrive\Desktop\Healthcare analysis\dataset\Cleaned_Hospital_Management_Records.csv", index=False)
df.to_excel(r"C:\Users\gopal\OneDrive\Desktop\Healthcare analysis\dataset\Cleaned_Hospital_Management_Records.xlsx", index=False)