In [62]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel(r"C:\Users\gopal\OneDrive\Desktop\Healthcare analysis\dataset\Cleaned_Hospital_Management_Records.xlsx")
df

,PatientID,PatientName,Age,Gender,PhoneNumber,Email,Address,City,State,RegistrationDate,...,AmountPaid,PendingAmount,PaymentMode,BillingDate,InsuranceProvider,FeedbackRating,Disease,AgeGroup,HospitalStays,PaymentStatus
0,45d3d0ef-38c3-49c9-a0bd-c68d9ee90a0f,Drishya Mammen,25,Female,2416034981,atank@arora-master.net,"40/720, Chakrabarti Circle, Bhilwara-385220",Tadipatri,Bihar,2024-10-03,...,59341.66,20837.50,Card,2025-03-13,Borah Inc,5,Flu,YoungAdult,126,Pending
1,afd50add-bab4-4e63-baca-3d92585821da,Rania Balay,44,Male,912947000000,kaladhruv@ratti.com,"66, Master Nagar, Mumbai-334047",Allahabad,Goa,2024-03-04,...,17818.53,153809.78,Insurance,2025-06-03,Unknown,2,Flu,Adult,67,Pending
2,d59f02b8-36be-4450-858f-22940e4d0a9b,Rhea Bhat,44,Other,1714094485,abhalla@batra.com,"013, Jayaraman Chowk, Tiruchirappalli-908041",Asansol,Chhattisgarh,2025-02-08,...,97493.48,86936.05,UPI,2025-04-05,Unknown,1,Cancer,Adult,39,Pending
3,d55dfe6a-0da2-4352-8321-15dda501a571,Elakshi Chatterjee,38,Other,910622000000,piyachacko@gmail.com,"H.No. 798, Das Nagar, Ahmednagar 130849",Kulti,Goa,2024-07-25,...,7275.76,31819.34,UPI,2025-02-24,Khalsa-Bala,4,COVID-19,Adult,93,Pending
4,1ce3dd94-318a-494d-8e91-e070237fe54f,Ayesha Toor,75,Female,5104023087,jivika45@hotmail.com,"H.No. 487, Koshy Ganj, Katihar 463550",Ramgarh,Tripura,2024-02-28,...,10372.96,7506.35,UPI,2025-04-20,Unknown,1,Hypertension,Elder,129,Pending
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,f3274e46-f1e9-4f1d-90e7-4a1f2e851088,Yasmin Kashyap,8,Other,8500267260,rbhandari@sachar-madan.com,"920, Sura Road, Thiruvananthapuram 767371",Guntur,Uttar Pradesh,2023-12-03,...,69308.77,89023.79,Insurance,2025-05-13,Unknown,5,Migraine,Child,344,Pending
9996,78d3a39a-3813-43cd-9415-c5214b6608d3,Eva Kumer,36,Other,915206000000,eshani15@yahoo.com,"56/345, Agarwal Nagar, Gandhinagar 446646",Kolhapur,Tamil Nadu,2024-11-08,...,26961.14,121367.98,UPI,2025-04-16,Raval-Halder,3,Cancer,Adult,22,Pending
9997,2c7c5224-b94d-4ba5-984b-bcbf74a9790d,Advik Korpal,16,Male,1777904014,surelakshi@hotmail.com,"H.No. 881, Konda, Kolhapur 490469",Mumbai,Haryana,2025-02-03,...,14904.67,59032.21,Cash,2025-05-08,Unknown,1,Diabetes,Child,68,Pending
9998,871dbc36-6a4d-43c2-8612-db28748a04c9,Keya Bera,77,Other,3759349906,barmanjhanvi@bedi.com,"H.No. 89, Samra Street, Hospet 521453",Unnao,Jharkhand,2023-08-02,...,42274.80,147564.18,UPI,2024-05-08,Unknown,4,Hypertension,Elder,257,Pending
9999,b56f0167-be46-4343-bfab-eadb76c0e9b9,Hazel Dara,3,Male,5754185464,emiryohannan@madan-ramakrishnan.com,"11, Sama Road, Secunderabad-902747",Berhampore,Odisha,2024-12-02,...,15856.86,10655.39,Cash,2025-03-25,Batta Group,5,Cancer,Child,37,Pending

PATIENT ANALYSIS

Total Patient

In [3]:
len(df)

10000

gender Distribution

In [4]:
df["Gender"].value_counts()

Gender
Female    3344
Male      3338
Other     3318
Name: count, dtype: int64

Avrage patient age

In [5]:
avg_patient = df["Age"].mean()
print("Average Patient Age :",avg_patient)

Average Patient Age : 45.6882

Youngest Patient

In [6]:
Youngest_Patient = df[df["Age"] == df["Age"].min()]
Youngest_Patient

,PatientID,PatientName,Age,Gender,PhoneNumber,Email,Address,City,State,RegistrationDate,...,AmountPaid,PendingAmount,PaymentMode,BillingDate,InsuranceProvider,FeedbackRating,Disease,AgeGroup,HospitalStays,PaymentStatus
110,711f49eb-177e-43c3-bfe5-a9364ad84f39,Fateh Loyal,1,Other,8851557187,ganeshjhanvi@gmail.com,"812, Handa Zila, North Dumdum-765521",Gandhidham,Assam,2023-09-29,...,174636.91,20973.29,Card,2025-06-10,Bhatia Group,1,Diabetes,Child,5,Pending
142,ba167bf9-c4f3-43a9-bb7b-893ba6c21bf5,Neelofar Kothari,1,Other,1587468118,drishyasavant@krishnan.biz,"52/647, Konda Marg, Hospet-141945",Saharanpur,Kerala,2025-04-14,...,61550.82,89062.47,Insurance,2025-05-20,Unknown,1,Asthma,Child,0,Pending
305,47e5e1ea-1d6a-423a-86d0-c279a99e80c0,Hrishita Dash,1,Female,3863733167,kgola@yahoo.com,"26/03, Kala Street, Gulbarga-472642",Kozhikode,Andhra Pradesh,2024-06-30,...,17610.82,123102.77,Card,2025-05-30,Gara-Kaul,4,Asthma,Child,3,Pending
501,86ae188b-ef97-4d86-a20c-a0d4ee3bac5e,Heer Dewan,1,Other,6900426008,reddybadal@sathe.com,"48, Bedi Nagar, Kulti-754005",Vadodara,Gujarat,2025-04-01,...,109694.11,106.53,Card,2025-05-27,Gaba-Upadhyay,4,Asthma,Child,15,Pending
804,df84a6fc-e161-4b3a-98d5-5dd79b08be01,Gokul Subramanian,1,Other,3635308711,lganguly@gmail.com,"087, Iyer Marg, Latur 563783",Tinsukia,Jharkhand,2024-08-16,...,75740.26,89365.09,Card,2025-05-25,"Tak, Butala and Sibal",2,Diabetes,Child,207,Pending
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9643,cc3eb7eb-2268-4985-8b21-22797c78e398,Amira Bansal,1,Male,913463000000,bijujani@badami.org,"01, Sankaran Street, Jalandhar 976258",Mira-Bhayandar,Manipur,2025-05-23,...,27686.53,13551.19,Cash,2025-06-02,"Keer, Wali and Ganesh",3,Migraine,Child,2,Pending
9737,6f2dbbdd-d202-4c3b-bac2-cc14661689e5,Anaya Barman,1,Other,911869000000,gchander@devan.com,"144, Luthra, Baranagar 011278",Madhyamgram,Gujarat,2023-11-07,...,243.32,4800.51,UPI,2024-12-04,"Tiwari, Babu and Rajagopal",4,Flu,Child,26,Pending
9787,af0dc252-3091-4234-9195-c567459e2330,Samaira Dayal,1,Other,910314000000,vamble@subramanian-ganguly.com,"H.No. 361, Rao Path, Udaipur-812993",Adoni,Chhattisgarh,2025-01-20,...,22305.70,158866.92,UPI,2025-05-18,Unknown,4,Flu,Child,16,Pending
9854,b0342b62-5b9d-451f-bda2-5ddc67754f2c,Abram Savant,1,Other,5356475825,osheth@tandon.com,"H.No. 682, Dasgupta Path, Medininagar-414660",Bikaner,Andhra Pradesh,2024-01-15,...,99667.53,95829.82,Cash,2024-10-09,Chakraborty-Ram,4,Migraine,Child,254,Pending
9948,118cb1a4-7afc-4746-b735-1e39127942c6,Yuvaan Venkataraman,1,Female,6155270896,manikyakrishnan@hotmail.com,"83, Shan Marg, Udaipur 850088",Sri Ganganagar,Odisha,2023-09-22,...,56850.35,74279.14,UPI,2025-01-17,Unknown,1,Hypertension,Child,323,Pending

In [7]:
youngest_Patient_Details = df.loc[df["Age"].idxmin()]
youngest_Patient_Details

PatientID            711f49eb-177e-43c3-bfe5-a9364ad84f39
PatientName                                   Fateh Loyal
Age                                                     1
Gender                                              Other
PhoneNumber                                    8851557187
Email                              ganeshjhanvi@gmail.com
Address              812, Handa Zila, North Dumdum-765521
City                                           Gandhidham
State                                               Assam
RegistrationDate                      2023-09-29 00:00:00
DoctorID             39fd8f11-8d68-414d-a8bd-35a291730e6b
DoctorName                                   Kabir Badami
Specialization                                 Pediatrics
Department                                     Pediatrics
DoctorPhone                                    9236135084
ConsultationFee                                      1385
AdmissionDate                         2025-06-05 00:00:00
DischargeDate                         2025-06-10 00:00:00
RoomType                                          Private
RoomNumber                                           R405
BedNumber                                             B22
AdmissionReason                                   Surgery
Diagnosis                                          Cancer
TreatmentGiven                      Totam quas iusto aut.
SurgeryRequired                                       Yes
SurgeryDate                           2025-06-08 00:00:00
FollowUpDate                          2025-06-15 00:00:00
TotalBillAmount                                  195610.2
AmountPaid                                      174636.91
PendingAmount                                    20973.29
PaymentMode                                          Card
BillingDate                           2025-06-10 00:00:00
InsuranceProvider                            Bhatia Group
FeedbackRating                                          1
Disease                                          Diabetes
AgeGroup                                            Child
HospitalStays                                           5
PaymentStatus                                     Pending
Name: 110, dtype: object

oldest Patient

In [8]:
oldest_Patient = df[df["Age"] == df["Age"].max()]
oldest_Patient

,PatientID,PatientName,Age,Gender,PhoneNumber,Email,Address,City,State,RegistrationDate,...,AmountPaid,PendingAmount,PaymentMode,BillingDate,InsuranceProvider,FeedbackRating,Disease,AgeGroup,HospitalStays,PaymentStatus
167,07926ff5-7c8f-4fef-9aa5-656f79736ec2,Divit Dave,90,Male,6489465033,priyanshsarraf@ray.com,"H.No. 977, Bakshi Circle, Asansol-498293",Chittoor,Himachal Pradesh,2025-01-04,...,9173.55,107885.82,Card,2025-06-11,Unknown,2,Migraine,Elder,12,Pending
201,e4c1c200-6470-4e80-893f-034a6610b78f,Ivana Khanna,90,Other,569541743,parinaaztripathi@jhaveri.com,"702, Magar Street, Belgaum-807204",Panihati,Gujarat,2023-11-27,...,92515.62,31380.69,Insurance,2025-01-18,"Tripathi, Jain and Chana",1,Diabetes,Elder,160,Pending
209,5606eee6-ca3c-4794-9e26-54663635cbc6,Misha Loke,90,Female,918575000000,doctoramani@gmail.com,"04/759, Thaker Path, Guwahati 863751",Cuttack,West Bengal,2024-06-11,...,52900.58,66109.62,Cash,2025-06-17,Unknown,1,Asthma,Elder,309,Pending
299,930b1aa9-2f77-4bca-89a6-f54d8353084e,Azad Lalla,90,Other,7152025641,dubeybadal@ramachandran.org,"H.No. 55, Kapadia Ganj, Vadodara-556709",Alwar,Chhattisgarh,2024-11-30,...,10489.40,60798.38,UPI,2025-06-05,Vyas-Krishnamurthy,3,Hypertension,Elder,79,Pending
321,e6ecb192-5bad-4904-a2de-c74ccdca5bd4,Nishith Varty,90,Other,4811986879,nitya73@behl-balasubramanian.com,"H.No. 126, Singh Marg, Karimnagar 850645",Kishanganj,Odisha,2024-09-27,...,60355.20,5373.54,UPI,2025-04-21,Unknown,1,Migraine,Elder,16,Pending
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9666,9f9bce9f-6ada-4cad-8f87-a2e16cd2a289,Nehmat Dara,90,Male,918776000000,kdubey@hegde.info,"99/186, Bobal Zila, Gudivada 114617",Bidhannagar,Assam,2024-12-29,...,11161.76,153542.00,UPI,2025-06-11,Korpal-Kohli,4,Asthma,Elder,3,Pending
9905,909ebc01-1419-4f7b-9bd9-42a71fd48089,Parinaaz Kaul,90,Female,1700620856,jrege@iyer.com,"702, Mangat Road, Imphal-301644",Panvel,Haryana,2024-10-28,...,1977.40,96660.88,UPI,2025-06-10,Unknown,1,Migraine,Elder,1,Pending
9940,fac237d6-3c87-4de9-a97b-cabc48aac993,Stuvan Bhatti,90,Male,9794047680,shayak43@borah-dayal.com,"99/55, Bhasin Zila, Kumbakonam-578986",Kumbakonam,Assam,2025-03-29,...,11999.89,24321.29,Card,2025-05-20,Unknown,2,Hypertension,Elder,2,Pending
9958,14bc0e0e-c49f-4069-bcb3-851813ca6831,Tanya Master,90,Male,1336554255,akapadia@gmail.com,"34, Joshi Zila, Howrah 287090",Farrukhabad,Arunachal Pradesh,2025-01-24,...,126429.14,21722.65,Cash,2025-05-15,Unknown,5,Diabetes,Elder,75,Pending
9994,0e57937d-2760-42f5-899c-b962fdb0f5e6,Taran Batta,90,Other,3151451611,kismat48@gmail.com,"57/263, Dyal Circle, Salem-371872",Bidhannagar,West Bengal,2024-03-19,...,92765.51,74008.82,Card,2025-04-19,"Kurian, Kanda and Warrior",3,Hypertension,Elder,174,Pending

Age Group Distribution

In [9]:
Age_distribution = df.value_counts("AgeGroup").reset_index(name="Total Patient")
Age_distribution

     AgeGroup  Total Patient
0       Elder           2792
1       Child           1949
2  YoungAdult           1947
3      Senior           1675
4       Adult           1637

City Wise Patient Distribution

In [10]:
City_wise_patient = df.value_counts("City").reset_index(name="Total Patient")
City_wise_patient

               City  Total Patient
0        Aurangabad             60
1         Ghaziabad             56
2            Purnia             46
3         Bhavnagar             45
4    Mira-Bhayandar             45
..              ...            ...
311        Thrissur             19
312           Latur             19
313           Morbi             19
314        Motihari             18
315        Amritsar             17

[316 rows x 2 columns]

In [11]:
City_wise_patient.nlargest(5, "Total Patient")

             City  Total Patient
0      Aurangabad             60
1       Ghaziabad             56
2          Purnia             46
3       Bhavnagar             45
4  Mira-Bhayandar             45

State wise Patients

In [12]:
state_Wise_Patients = df.value_counts("State").reset_index(name="Patient Name")
state_Wise_Patients

                State  Patient Name
0           Jharkhand           386
1              Odisha           384
2         Uttarakhand           382
3             Mizoram           381
4        Chhattisgarh           371
5             Tripura           369
6               Bihar           368
7      Madhya Pradesh           368
8          Tamil Nadu           367
9              Sikkim           361
10        West Bengal           361
11             Kerala           361
12             Punjab           360
13            Haryana           358
14          Karnataka           357
15        Maharashtra           357
16            Manipur           355
17          Telangana           354
18           Nagaland           349
19              Assam           349
20  Arunachal Pradesh           347
21          Meghalaya           347
22   Himachal Pradesh           345
23                Goa           344
24          Rajasthan           338
25     Andhra Pradesh           335
26            Gujarat           330
27      Uttar Pradesh           316

State Wise Total Patients

In [13]:
state_Wise_Patients.head(10)

            State  Patient Name
0       Jharkhand           386
1          Odisha           384
2     Uttarakhand           382
3         Mizoram           381
4    Chhattisgarh           371
5         Tripura           369
6           Bihar           368
7  Madhya Pradesh           368
8      Tamil Nadu           367
9          Sikkim           361

Monthly Total Patient

In [14]:
month_wise_patients = (
    df.groupby(df["AdmissionDate"].dt.month_name())["PatientID"]
      .count()
)
month_wise_patients

AdmissionDate
April        1246
August        416
December      755
February      796
January       821
July          359
June         1406
March        1117
May          1538
November      574
October       556
September     416
Name: PatientID, dtype: int64

Year Wise Total Patient

In [15]:
Year_wise_patient = (
    df.groupby(df["AdmissionDate"].dt.year)["PatientID"].count().reset_index(name="Total Patient")
)
Year_wise_patient

   AdmissionDate  Total Patient
0           2023            418
1           2024           3955
2           2025           5627

DOCTOR ANALYSIS

Total number of doctors

In [16]:
Total_Doctors = df["DoctorName"].nunique()
Total_Doctors

9465

Number of doctors by specialization

In [17]:
df.groupby("Specialization")["DoctorName"].count().reset_index(name="Total doctors").sort_values(by="Total doctors")

     Specialization  Total doctors
0        Cardiology           1378
1               ENT           1378
4       Orthopedics           1398
6           Surgery           1423
5        Pediatrics           1446
3         Neurology           1484
2  General Medicine           1493

Which doctors treated the most Patient

In [18]:
df.groupby("DoctorName")["PatientID"].count().reset_index(name="Total").sort_values(by="Total", ascending=False).head(1)

     DoctorName  Total
756  Anahi Kala      4

Department Wise Total DOctor

In [19]:
df.groupby("Department")["DoctorName"].count().reset_index(name="Total_Doctors")

   Department  Total_Doctors
0  Cardiology           1367
1         ENT           1419
2     General           1473
3   Neurology           1440
4       Ortho           1455
5  Pediatrics           1420
6     Surgery           1426

Average consultation fee

In [20]:
print("Average consultantion Fee", df["ConsultationFee"].mean())

Average consultantion Fee 898.1149

DISEASE ANALYSIS

Most common disease

In [21]:
common_disease = df["Disease"].mode()[0]
print("Most Common Disease : ", common_disease)

Most Common Disease :  Fracture

Top 10 diseases

In [22]:
top_Disease = (df["Disease"].value_counts().reset_index())
top_Disease.columns = ["Disease", "patients"]
top_Disease.head(10)

        Disease  patients
0      Fracture      1272
1           Flu      1270
2      Diabetes      1258
3      Migraine      1250
4        Cancer      1244
5        Asthma      1243
6      COVID-19      1239
7  Hypertension      1224

Disease distribution by gender

In [23]:
disease_disrtibution = pd.crosstab(df["Disease"], df["Gender"])
disease_disrtibution

Gender        Female  Male  Other
Disease
Asthma           405   426    412
COVID-19         403   430    406
Cancer           436   378    430
Diabetes         417   437    404
Flu              417   426    427
Fracture         460   423    389
Hypertension     405   405    414
Migraine         401   413    436

Disease distribution by age group

In [24]:
pd.crosstab(df["Disease"], df["AgeGroup"])

AgeGroup      Adult  Child  Elder  Senior  YoungAdult
Disease
Asthma          168    254    371     222         228
COVID-19        198    230    341     204         266
Cancer          225    248    322     187         262
Diabetes        207    234    359     222         236
Flu             207    248    357     205         253
Fracture        222    263    350     216         221
Hypertension    191    236    334     221         242
Migraine        219    236    358     198         239

Disease distribution by city

In [25]:
df.value_counts("City")

City
Aurangabad        60
Ghaziabad         56
Purnia            46
Bhavnagar         45
Mira-Bhayandar    45
                  ..
Thrissur          19
Latur             19
Morbi             19
Motihari          18
Amritsar          17
Name: count, Length: 316, dtype: int64

HOSPITAL STAY ANALYSIS

Average hospital Stay

In [28]:
df["HospitalStays"].mean()

np.float64(91.4568)

Longest hospital stays

In [30]:
df["HospitalStays"].max()

np.int64(692)

Shortest hospital Stays

In [31]:
df["HospitalStays"].min()

np.int64(0)

In [34]:
df.groupby("Disease")["HospitalStays"].mean().reset_index(name="Avg. days").sort_values(by="Avg. days", ascending=False)

        Disease  Avg. days
4           Flu  94.539370
0        Asthma  93.195495
5      Fracture  92.759434
7      Migraine  91.882400
3      Diabetes  91.597774
6  Hypertension  91.402778
2        Cancer  89.972669
1      COVID-19  86.186441

Average stay by department

In [36]:
df.groupby("Department")["HospitalStays"].mean().reset_index(name="Avg.days").sort_values(by="Avg.days")

   Department   Avg.days
2     General  84.871012
5  Pediatrics  90.280986
0  Cardiology  90.831017
4       Ortho  90.895533
6     Surgery  93.328892
1         ENT  94.961240
3   Neurology  95.206944

Financial analysis

Total hospital revenue

In [41]:
Total_revenue = df["TotalBillAmount"].sum()
print("Total Hospital Revenue :Rs.{:,.2f}".format(Total_revenue))

Total Hospital Revenue :Rs.1,033,409,702.90

Average Bill

In [42]:
Avg_Bill = df["TotalBillAmount"].mean()
print("Average_billAmount : Rs.{:,.2f}".format(Avg_Bill))

Average_billAmount : Rs.103,340.97

Highest Bill

In [43]:
Highest_Bill = df["TotalBillAmount"].max()
print("Highest_BillAmount : Rs.{:,.2f}".format(Highest_Bill))

Highest_BillAmount : Rs.199,980.06

Lowest Bill

In [44]:
Lowest_bill = df["TotalBillAmount"].min()
print("Lowest Bill Amount : Rs.{:,.2f}".format(Lowest_bill))

Lowest Bill Amount : Rs.5,034.30

Pending amount

In [45]:
Pending_Amount = df["PendingAmount"].sum()
print("Total Pending Amount : Rs.{:,.2f}".format(Pending_Amount))

Total Pending Amount : Rs.523,183,004.55

Highest Pending Amount and details

In [46]:
highest_pending_Amount = df.loc[df["PendingAmount"].idxmax()]
print(highest_pending_Amount[["PatientID", "PatientName", "PendingAmount"]])

PatientID        11baffc5-5292-49e1-8030-db1b5a4f55fb
PatientName                                Anahi Sura
PendingAmount                               194625.76
Name: 5308, dtype: object

Lowest Pending Amount

In [48]:
lowest_pending_Amount = df.loc[df["PendingAmount"].idxmin()]
print(lowest_pending_Amount[["PatientID", "PatientName", "PendingAmount"]])

PatientID        e82d48c7-c490-4722-8e29-7596e4ed7e81
PatientName                             Indrans Ratta
PendingAmount                                    1.95
Name: 8785, dtype: object

Revenue by Payment Mode

In [50]:
Revenue = df.groupby("PaymentMode")["TotalBillAmount"].sum().reset_index(name="Total Amount")
Revenue["Total Amount"] = Revenue["Total Amount"].map("{:,.2f}".format)
print(Revenue)

  PaymentMode    Total Amount
0        Card  255,437,119.23
1        Cash  257,764,960.84
2   Insurance  254,867,905.60
3         UPI  265,339,717.23

SURGERY ANALYSIS

Total Surgery

In [54]:
Total_Surgery = df["SurgeryRequired"].value_counts()["Yes"]
print("Total Surgery Patient : ", Total_Surgery)

Total Surgery Patient :  5047

Disease Wise Surgery

In [55]:
pd.crosstab(df['Disease'], df["SurgeryRequired"])

SurgeryRequired   No  Yes
Disease
Asthma           595  648
COVID-19         608  631
Cancer           598  646
Diabetes         664  594
Flu              639  631
Fracture         636  636
Hypertension     609  615
Migraine         604  646

Department Wise Surgery

In [56]:
Department_Wise_Surgery = pd.crosstab(df["Department"], df["SurgeryRequired"])
Department_Wise_Surgery

SurgeryRequired   No  Yes
Department
Cardiology       671  696
ENT              691  728
General          748  725
Neurology        729  711
Ortho            733  722
Pediatrics       716  704
Surgery          665  761

Registration trend

In [ ]:
df["RegistrationDate"].dt.month_name().value_counts().sort_index().

RegistrationDate
April        833
August       874
December     823
February     823
January      864
July         818
June         816
March        807
May          840
November     806
October      871
September    825
Name: count, dtype: int64

In [60]:
Monthly_Trend = (
    df.groupby(df["RegistrationDate"].dt.month)["PatientID"].count().reset_index(name="Total Patient")
)
Monthly_Trend["Month"] = ["January", "February", "March", "April", "MAy", "June", "July", "August",
                          "September", "october", "November", "December"]
Monthly_Trend = Monthly_Trend[["Month", "Total Patient"]]
print(Monthly_Trend)

        Month  Total Patient
0     January            864
1    February            823
2       March            807
3       April            833
4         MAy            840
5        June            816
6        July            818
7      August            874
8   September            825
9     october            871
10   November            806
11   December            823

Admission Trend

In [61]:
admission_trend = (
    df.groupby(df["AdmissionDate"].dt.month)["PatientID"].count().reset_index(name="Total Patient")
)
admission_trend["Month"] = ["January", "February", "March", "April", "MAy", "June", "July", "August",
                          "September", "october", "November", "December"]

admission_trend = admission_trend[["Month","Total Patient"]]
print(admission_trend)

        Month  Total Patient
0     January            821
1    February            796
2       March           1117
3       April           1246
4         MAy           1538
5        June           1406
6        July            359
7      August            416
8   September            416
9     october            556
10   November            574
11   December            755

In [63]:
correlation = df.select_dtypes(include=np.number).corr()
correlation

,Age,PhoneNumber,DoctorPhone,ConsultationFee,TotalBillAmount,AmountPaid,PendingAmount,FeedbackRating,HospitalStays
Age,1.000000,0.023789,0.002206,-0.012157,0.007001,0.001865,0.006998,0.005857,-0.016446
PhoneNumber,0.023789,1.000000,0.001479,0.010232,0.006153,0.004686,0.003129,0.001322,0.025096
DoctorPhone,0.002206,0.001479,1.000000,0.022738,-0.003214,0.002817,-0.006854,-0.003217,0.022275
ConsultationFee,-0.012157,0.010232,0.022738,1.000000,-0.021355,-0.010612,-0.016462,-0.007971,0.002415
TotalBillAmount,0.007001,0.006153,-0.003214,-0.021355,1.000000,0.630441,0.638577,-0.016978,-0.000836
AmountPaid,0.001865,0.004686,0.002817,-0.010612,0.630441,1.000000,-0.194775,0.000647,-0.002701
PendingAmount,0.006998,0.003129,-0.006854,-0.016462,0.638577,-0.194775,1.000000,-0.022095,0.001622
FeedbackRating,0.005857,0.001322,-0.003217,-0.007971,-0.016978,0.000647,-0.022095,1.000000,0.010284
HospitalStays,-0.016446,0.025096,0.022275,0.002415,-0.000836,-0.002701,0.001622,0.010284,1.000000